red_team:
  locations:
    check_block2_kfs:
      waypoints:
        - x: "3.0"
          y: "-4.2"
          yaw: "math.pi / 2.0"

    block_0_center:
      waypoints:
        - x: "3.0"
          y: "-3.4"
          yaw: "math.pi / 2.0"

    ramp_entrance:
      waypoints:
        - x: "5.25"
          y: "2.75"
          yaw: "math.pi / 2.0"

    ramp_end_platform:
      waypoints:
        - x: "5.25"
          y: "5.25"
          yaw: "math.pi / 2.0"

    tick_tack_toe_rack:
      waypoints:
        - x: "1.30"
          y: "5.2"
          yaw: "math.pi"

blue_team:
  locations:
    check_block2_kfs:
      waypoints:
        - x: "-3.0"
          y: "-4.2"
          yaw: "math.pi / 2.0"

    block_0_center:
      waypoints:
        - x: "-3.0"
          y: "-3.4"
          yaw: "math.pi / 2.0"

    ramp_entrance:
      waypoints:
        - x: "-5.25"
          y: "3.3"
          yaw: "math.pi / 2.0"

    ramp_end_platform:
      waypoints:
        - x: "-5.25"
          y: "4.8"
          yaw: "math.pi / 2.0"

    tick_tack_toe_rack:
      waypoints:
        - x: "-3.0"
          y: "5.5"
          yaw: "math.pi / 2.0"
