# GetHighLevelPlan.srv
# Request from the BT to the High-Level Planner (Dijkstra)

# The robot's current state
uint8 current_block_id
uint8 current_facing_block_id
uint8 current_kfs_count
bool gripper_has_kfs

---
# Response to the BT

# The exact sequence name from plan.yaml
string sequence_name

# The parameters for that sequence, serialized as a JSON string
# Example: "{\"target_block_id\": 5}"
string sequence_params_json
