controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    extrusion_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["left_front_wheel_joint", "left_back_wheel_joint"]
    right_wheel_names: ["right_front_wheel_joint", "right_back_wheel_joint"]
    wheel_separation: 0.76
    wheel_radius: 0.05
    wheels_per_side: 2
    publish_rate: 30.0
    odom_frame_id: odom
    base_frame_id: base_footprint
    enable_odom_tf: false
    cmd_vel_timeout: 0.5
    use_stamped_vel: false

extrusion_controller:
  ros__parameters:
    joints:
      - left_front_extrusion_joint
      - right_front_extrusion_joint
      - left_back_extrusion_joint
      - right_back_extrusion_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

gripper_controller:
  ros__parameters:
    joints:
      - left_gripper_joint
      - right_gripper_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

arm_controller:
  ros__parameters:
    joints:
      - left_arm_joint
      - right_arm_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
